#
# Blog Settings
#
author: Ferran Salguero
description: 
url: http://fsalguero.github.io/
title: Ferran Salguero
subtitle: 
gravatar_url: 
subscribe_rss: 

# Github repositories
github_user: fsalguero
github_repo_url: https://github.com/fsalguero/fsalguero.github.io

# Twitter
twitter_user: ferransalguero
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: fsalguero
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-53197884-1


#
# Jekyll Settings
#
markdown: redcarpet
redcarpet:
  extensions: ["tables"]
permalink: /archive/:year/:month/:day/:title/
paginate: 20
paginate_path: "page/:num"
category_dir: categories

gems:
  - jekyll-redirect-from
  - jekyll-sitemap
