#
# Blog Settings
#
author: Ferran Salguero
description: 
url: http://ferransalguero.github.io
title: Ferran Salguero
subtitle: 
gravatar_url: 
subscribe_rss: /atom.xml

# Github repositories
github_user: fsalguero
github_repo_url: https://github.com/fsalguero/fsalguero.github.io

# Twitter
twitter_user: ferransalguero
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: ferransalguero
disqus_show_comment_count: true

# Google Analytics
google_analytics_tracking_id: UA-53197884-1


#
# Jekyll Settings
#
timezone: Europe/Berlin
markdown: kramdown
# redcarpet:
#   extensions: ["tables"]
#permalink: /archive/:year/:month/:day/:title/
permalink: /blog/:title/
paginate: 20
paginate_path: "/blog/page/:num"
category_dir: categories
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
sass:
    style: compressed

gems:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-coffeescript


collections:
  portfolios:
    output: true
    permalink: /portfolio/:path.html